stages:
  - build
  - test
build:
  stage: build
  before_script: 
  - npm install
  - npm install axios
  script:
    - npm run build
test:
  stage: test
  before_script: 
    - npm install 
  script: 
    - npm run test
