export const INPUT_SUCCESS = "INPUT_SUCCESS";
export const INPUT_FAIL = "INPUT_FAIL";

export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_FAIL = "SESSION_FAIL";
export const MESSAGE_SUCCESS = "MESSAGE_SUCESS";
export const MESSAGE_FAIL = "MESSAGE_FAIL";
export const TOGGLE_SUCCESS = "TOGGLE_SUCCESS";
export const TOGGLE_FAIL = "TOGGLE_FAIL";

export const LINK_SUCCESS = "LINK_SUCCESS";

export const LANG_SUCCESS = "LANG_SUCCESS";

export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";

export const QUESTION_SUCCESS = "QUESTION_SUCCESS";

export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const RESET_STATE = "RESET_STATE";

export const STORED_FAIL = "STORED_FAIL";
