export const INPUT_SUCCESS = "INPUT_SUCCESS";
export const INPUT_FAIL = "INPUT_FAIL";

export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_FAIL = "SESSION_FAIL";
export const MESSAGE_SUCCESS = "MESSAGE_SUCESS";
export const MESSAGE_FAIL = "MESSAGE_FAIL";
export const TOGGLE_SUCCESS = "TOGGLE_SUCCESS";
export const TOGGLE_FAIL = "TOGGLE_FAIL";
